### ISSUE TITLE
Vcell container does not handle spaces in file names

### ISSUE THREAD

**Issue by bilalshaikh42** [biosimulators/Biosimulators_VCell#54]
To Reproduce: 
1. Go to run.biosimulations.dev and submit a simulation with the attached archive containing a  space in the name  running on vcell (change file extension from zip to omex)
2.  Repeat with tellurium 
3. See that VCELL errors with "provided omex not present" while tellurium runs fine 

[Caravagna-J-Theor-Biol-2010-tumor-suppressive-oscillations (1).zip](https://github.com/biosimulators/Biosimulators_VCell/files/5989594/Caravagna-J-Theor-Biol-2010-tumor-suppressive-oscillations.1.zip)

**Comment by gmarupilla** [comment]
@bilalshaikh42 I looked into it. If spaces are present in any path, that path needs to be provided in quotes (""). Because, if not provided in quotes, it'll take space-separated strings as different arguments and will throw all kinds of errors (like omex not found, omex not present, invalid argument, etc)

When we need to modify sbatch script template to use explicit quotes in all paths, do you want me to go ahead and do that?

**Comment by gmarupilla** [comment]
@bilalshaikh42  I fixed it in local, it will be fixed on HPC container whenever newer version of VCell CLI (container) is pushed to GHCR.

**Comment by bilalshaikh42** [comment]
Is this not the repo for the container?

**Comment by gmarupilla** [comment]
Yes, It is the repo to make the container. But changes were being merged from the main VCell master branch.

**Comment by bilalshaikh42** [comment]
Will the vcell master repo be pulled into this repo?

**Comment by gmarupilla** [comment]
After merging #55 the VCell master repo code should be merged into the dev branch of this repo.

**Comment by gmarupilla** [comment]
Fixed in 40e1ab25a0dbf6bfa28b0026136a5b0dbb6459a5
